name: jWidget 2
input: src
output: dist

references:
  # External references
  lodash:
    label: Lodash
    href: https://lodash.com
  underscore:
    label: Underscore.js
    href: http://underscorejs.org
  jquery:
    label: jQuery
    href: http://api.jquery.com
  JQuery:
    href: http://api.jquery.com
  Promise:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
  PromiseAll:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
    label: Promise.all
  PromiseRace:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race
    label: Promise.race
  PromiseThen:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then
    label: Promise.then
  PromiseCatch:
    href: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch
    label: Promise.catch
  jqXHR:
    href: http://api.jquery.com/jquery.ajax/
  Thenable:
    href: https://www.npmjs.com/package/@types/es6-promise
  setTimeout:
    href: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout
  clearTimeout:
    href: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearTimeout
  setInterval:
    href: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval
  clearInterval:
    href: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/clearInterval

  # Pages
  DocumentationRoot:
    file: doc
    label: Documentation root

  # Terms
  falsy:
    file: jwidget
    symbol: isFalsy
  truthy:
    file: jwidget
    symbol: isTruthy
  destroyed:
    file: jwidget/Destroyable
    member: destroy
  destroying:
    file: jwidget/Destroyable
    member: destroy
  destruction:
    file: jwidget/Destroyable
    member: destroy
  destroys:
    file: jwidget/Destroyable
    member: destroy
  dispatched:
    file: jwidget/IDispatcher
    member: dispatch
  dispatches:
    file: jwidget/IDispatcher
    member: dispatch

  # Core
  CoreUtils:
    file: jwidget
  Binding:
    file: jwidget
    symbol: Binding
  CollectionFlags:
    file: jwidget
    symbol: CollectionFlags
  TWOWAY:
    file: jwidget
    symbol: Binding
  cmp:
    file: jwidget
    symbol: cmp
  destroyFunction:
    file: jwidget
    symbol: destroy
    label: destroy
  newIid:
    file: jwidget
    symbol: newIid

  # ArrayUtils
  backEvery:
    file: jwidget/ArrayUtils
    symbol: backEvery

  # Destroyable
  destroy:
    file: jwidget/Destroyable
    member: destroy
  baseDestroy:
    file: jwidget/Destroyable
    member: destroy
    label: destroy

  # IClass
  own:
    file: jwidget/IClass
    member: own

  # Class
  destroyObject:
    file: jwidget/Class
    member: destroyObject

  # Listenable
  listenMethod:
    file: jwidget/Listenable
    member: listen
    label: listen

  # Dispatcher
  dispatch:
    file: jwidget/IDispatcher
    member: dispatch

  # Bindable
  getOfBindable:
    file: jwidget/Bindable
    member: get
    label: get
  mapOfBindable:
    file: jwidget/Bindable
    member: map
    label: map

  # IProperty
  ownValue:
    file: jwidget/IProperty
    member: ownValue

  # Property
  setOfProperty:
    file: jwidget/IProperty
    member: set
    label: set

  # Switcher
  initOfSwitcher:
    file: jwidget/Switcher
    symbol: Switcher.Config
    member: init
    label: init

  doneOfSwitcher:
    file: jwidget/Switcher
    symbol: Switcher.Config
    member: done
    label: done

  # Component
  beforeRender:
    file: jwidget/Component
    member: beforeRender

  afterRender:
    file: jwidget/Component
    member: afterRender

  getElement:
    file: jwidget/Component
    member: getElement

  renderTo:
    file: jwidget/Component
    member: renderTo

  # Collection
  collections:
    file: jwidget/ReadonlyCollection
    label: Collections

  # List
  findOfList:
    file: jwidget/ReadonlyList
    member: find
    label: find

  # Mappers
  mappers:
    file: jwidget/mapper/AbstractMapper
    label: Mappers

  ListMapper:
    file: jwidget/mapper/list

  MapMapper:
    file: jwidget/mapper/map

  SetMapper:
    file: jwidget/mapper/set

  createMapper:
    file: jwidget/mapper/collection
    symbol: createMapper

  mapCollection:
    file: jwidget/mapper/collection
    symbol: mapCollection

  mapList:
    file: jwidget/mapper/list
    symbol: mapList

  mapMap:
    file: jwidget/mapper/map
    symbol: mapMap

  mapSet:
    file: jwidget/mapper/set
    symbol: mapSet

  # Filterers
  filterers:
    file: jwidget/filterer/AbstractFilterer
    label: Filterers

  ListFilterer:
    file: jwidget/filterer/list

  MapFilterer:
    file: jwidget/filterer/map

  SetFilterer:
    file: jwidget/filterer/set

  createFilterer:
    file: jwidget/filterer/collection
    symbol: createFilterer

  filterCollection:
    file: jwidget/filterer/collection
    symbol: filterCollection

  filterList:
    file: jwidget/filterer/list
    symbol: filterList

  filterMap:
    file: jwidget/filterer/map
    symbol: filterMap

  filterSet:
    file: jwidget/filterer/set
    symbol: filterSet

  # Counters
  counters:
    file: jwidget/counter/AbstractCounter
    label: Counters

  ListCounter:
    file: jwidget/counter/list

  MapCounter:
    file: jwidget/counter/map

  SetCounter:
    file: jwidget/counter/set

  createCounter:
    file: jwidget/counter/collection
    symbol: createCounter

  countCollection:
    file: jwidget/counter/collection
    symbol: countCollection

  countList:
    file: jwidget/counter/list
    symbol: countList

  countMap:
    file: jwidget/counter/map
    symbol: countMap

  countSet:
    file: jwidget/counter/set
    symbol: countSet

  # Indexers
  indexers:
    file: jwidget/indexer/AbstractIndexer
    label: Indexers

  ListIndexer:
    file: jwidget/indexer/list

  MapIndexer:
    file: jwidget/indexer/map

  SetIndexer:
    file: jwidget/indexer/set

  createIndexer:
    file: jwidget/indexer/collection
    symbol: createIndexer

  indexCollection:
    file: jwidget/indexer/collection
    symbol: indexCollection

  indexList:
    file: jwidget/indexer/list
    symbol: indexList

  indexMap:
    file: jwidget/indexer/map
    symbol: indexMap

  indexSet:
    file: jwidget/indexer/set
    symbol: indexSet

  # ConvertersToSet
  convertersToSet:
    file: jwidget/convertertoset/AbstractConverterToSet
    label: Converters to set

  ListConverterToSet:
    file: jwidget/convertertoset/list

  MapConverterToSet:
    file: jwidget/convertertoset/map

  SetConverterToSet:
    file: jwidget/convertertoset/set

  createConverterToSet:
    file: jwidget/convertertoset/collection
    symbol: createConverterToSet

  collectionToSet:
    file: jwidget/convertertoset/collection
    symbol: collectionToSet

  listToSet:
    file: jwidget/convertertoset/list
    symbol: listToSet

  mapToSet:
    file: jwidget/convertertoset/map
    symbol: mapToSet

  setToSet:
    file: jwidget/convertertoset/set
    symbol: setToSet

  # ConvertersToList
  convertersToList:
    file: jwidget/convertertolist/AbstractConverterToList
    label: Converters to list

  ListConverterToList:
    file: jwidget/convertertolist/list

  MapConverterToList:
    file: jwidget/convertertolist/map

  SetConverterToList:
    file: jwidget/convertertolist/set

  createConverterToList:
    file: jwidget/convertertolist/collection
    symbol: createConverterToList

  collectionToList:
    file: jwidget/convertertolist/collection
    symbol: collectionToList

  listToList:
    file: jwidget/convertertolist/list
    symbol: listToList

  mapToList:
    file: jwidget/convertertolist/map
    symbol: mapToList

  setToList:
    file: jwidget/convertertolist/set
    symbol: setToList

  # SortersComparing
  sortersComparing:
    file: jwidget/sortercomparing/AbstractSorterComparing
    label: Sorters (comparing)

  ListSorterComparing:
    file: jwidget/sortercomparing/list

  MapSorterComparing:
    file: jwidget/sortercomparing/map

  SetSorterComparing:
    file: jwidget/sortercomparing/set

  createSorterComparing:
    file: jwidget/sortercomparing/collection
    symbol: createSorterComparing

  sortCollectionComparing:
    file: jwidget/sortercomparing/collection
    symbol: sortCollectionComparing

  sortListComparing:
    file: jwidget/sortercomparing/list
    symbol: sortListComparing

  sortMapComparing:
    file: jwidget/sortercomparing/map
    symbol: sortMapComparing

  sortSetComparing:
    file: jwidget/sortercomparing/set
    symbol: sortSetComparing

  # Observers
  observers:
    file: jwidget/observer/AbstractObserver
    label: Observers

  ListObserver:
    file: jwidget/observer/list

  MapObserver:
    file: jwidget/observer/map

  SetObserver:
    file: jwidget/observer/set

  createObserver:
    file: jwidget/observer/collection
    symbol: createObserver

  # Inserters
  inserters:
    file: jwidget/inserter/list
    label: Inserters

  ListInserter:
    file: jwidget/inserter/list

  MapInserter:
    file: jwidget/inserter/map

  # Mergers
  mergers:
    file: jwidget/merger/list
    label: Mergers

  ListMerger:
    file: jwidget/merger/list

  mergeLists:
    file: jwidget/merger/list
    symbol: mergeLists

  mergeNoSync:
    file: jwidget/merger/list
    symbol: mergeNoSync

  # Reversers
  reversers:
    file: jwidget/reverser/list
    label: Reversers

  ListReverser:
    file: jwidget/reverser/list

  reverseList:
    file: jwidget/reverser/list
    symbol: reverseList

  # Tutorials
  TutorialIndex:
    file: tutorial
    label: jWidget 2 tutorials

  tutorial1:
    file: tutorials/tutorial1
    label: Tutorial. Part 1. Model and view

  tutorial2:
    file: tutorials/tutorial2
    label: Tutorial. Part 2. Child component collections

  tutorial3:
    file: tutorials/tutorial3
    label: Tutorial. Part 3. Named child components

  tutorial4:
    file: tutorials/tutorial4
    label: Tutorial. Part 4. Messages

  tutorial5:
    file: tutorials/tutorial5
    label: Tutorial. Part 5. Properties

  tutorial6:
    file: tutorials/tutorial6
    label: Tutorial. Part 6. Collection bindings

  philosophy:
    file: tutorials/philosophy
    label: jWidget philosophy

includes:
  DocumentationIndex: |
    <div class="container-fluid">
      <h5>%DocumentationRoot</h5>
      <div class="row">
        <div class="col-4">
          <h5>Utilities</h5>
          <ul class="list-unstyled">
            <li>%CoreUtils</li>
            <li>%ArrayUtils</li>
            <li>%DomUtils</li>
            <li>%IterableUtils</li>
            <li>%MapUtils</li>
            <li>%SetUtils</li>
            <li>%StringUtils</li>
          </ul>
          <h5>Core interfaces</h5>
          <ul class="list-unstyled">
            <li>%Destroyable</li>
            <li>%Listenable</li>
            <li>%Bindable</li>
            <li>%DestroyableBindable</li>
          </ul>
        </div>
        <div class="col-4">
          <h5>Auxiliary interfaces</h5>
          <ul class="list-unstyled">
            <li>%Some</li>
          </ul>
          <h5>Core classes and their interfaces</h5>
          <ul class="list-unstyled">
            <li>%Class, %IClass</li>
            <li>%Dispatcher, %IDispatcher</li>
            <li>%Property, %IProperty</li>
          </ul>
          <h5>UI core</h5>
          <ul class="list-unstyled">
            <li>%Component</li>
            <li>%Renderable</li>
            <li>%template</li>
            <li>%listen</li>
          </ul>
        </div>
        <div class="col-4">
          <h5>Model bindings for %Property</h5>
          <ul class="list-unstyled">
            <li>%Copier</li>
            <li>%Mapper</li>
            <li>%Switcher</li>
          </ul>
          <h5>View bindings for %Property</h5>
          <ul class="list-unstyled" style="column-count: 2">
            <li>%bindAttr</li>
            <li>%bindClass</li>
            <li>%bindCss</li>
            <li>%bindDisplay</li>
            <li>%bindHtml</li>
            <li>%bindProp</li>
            <li>%bindRadio</li>
            <li>%bindText</li>
            <li>%bindVal</li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-8">
          <h5>Collections</h5>
          <table class="table table-sm">
            <tbody>
              <tr>
                <td>%ReadonlyBindableArray</td>
                <td>%ReadonlyBindableMap</td>
                <td>%ReadonlyBindableSet</td>
              </tr>
              <tr>
                <td>%DestroyableReadonlyBindableArray</td>
                <td>%DestroyableReadonlyBindableMap</td>
                <td>%DestroyableReadonlyBindableSet</td>
              </tr>
              <tr>
                <td>%IBindableArray</td>
                <td>%IBindableMap</td>
                <td>%IBindableSet</td>
              </tr>
              <tr>
                <td>%BindableArray</td>
                <td>%BindableMap</td>
                <td>%BindableSet</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-4">
          <h5>Collection bindings</h5>
          <ul class="list-unstyled" style="column-count: 2">
            <li>%ArrayFilterer</li>
            <li>%ArrayInserter</li>
            <li>%ArrayMapper</li>
            <li>%ArrayMerger</li>
            <li>%ArrayReverser</li>
            <li>%ArrayValueCollector</li>
            <li>%MapFilterer</li>
            <li>%MapInserter</li>
            <li>%MapKeyCollector</li>
            <li>%MapMapper</li>
            <li>%MapValueCollector</li>
            <li>%SetConverterToArray</li>
            <li>%SetFilterer</li>
            <li>%SetIndexer</li>
            <li>%SetMapper</li>
            <li>%SetMatchingValueCounter</li>
            <li>%SetSorter</li>
            <li>%SetValueCollector</li>
          </ul>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-4">
          <h5>Routing</h5>
          <ul class="list-unstyled">
            <li>%hash</li>
            <li>%Router</li>
            <li>%RouteRedirector</li>
            <li>%RoutingNode</li>
            <li>%UIRouter</li>
            <li>%Endpoint</li>
          </ul>
          <h5>Destroyable adapters</h5>
          <ul class="list-unstyled">
            <li>%Destructor</li>
            <li>%Interval</li>
          </ul>
        </div>
        <div class="col-4">
          <h5>AJAX and asyncronous operations</h5>
          <ul class="list-unstyled">
            <li>%CancelToken</li>
            <li>%defer</li>
            <li>%request</li>
          </ul>
          <h5>Other tools</h5>
          <ul class="list-unstyled">
            <li>%DomInserter</li>
            <li>%DomTemplate</li>
            <li>%HtmlTemplate</li>
          </ul>
        </div>
        <div class="col-4">
          <h5>References (low level stuff)</h5>
          <ul class="list-unstyled">
            <li>%AbstractTemplate</li>
            <li>%dummyDestroyable</li>
            <li>%dummyDispatcher</li>
            <li>%ArraySpliceResult</li>
            <li>%TemplateOutput</li>
          </ul>
        </div>
      </div>
    </div>

  TutorialIndex: |
    <div class="container-fluid">
      <h5>%TutorialIndex</h5>
      <ul>
        <li>%tutorial1</li>
        <li>%tutorial2</li>
        <li>%tutorial3</li>
        <li>%tutorial4</li>
        <li>%tutorial5</li>
        <li>%tutorial6</li>
      </ul>
      <hr>
      <ul>
        <li>%philosophy</li>
      </ul>
    </div>

  DispatcherExample: |
    <p>It is smart to store a dispatcher as %IDispatcher internally, and expose it as %Listenable externally to deny direct
    control over the dispatcher by its listeners.</p>
    <pre>
    class Example {
        private _onChange = new %Dispatcher<number>();

        get onChange(): %Listenable<number> {
            return this._onChange;
        }

        // ...

            // We can't dispatch public onChange, but we can dispatch private _onChange
            this._onChange.%dispatch(value);

        // ...
    }
    </pre>

  PropertyExample: |
    <p>It is sometimes smart to store the property as %IProperty internally, and expose it as %Bindable or
    %DestroyableBindable externally to deny direct control over the property by the clients.</p>
    <pre>
    class Example {
        private _size = new %Property<number>(0);

        get size(): %Bindable<number> {
            return this._size;
        }

        // ...

            // We can't set public size, but we can set private _size
            this._size.%set(value);

        // ...
    }
    </pre>
